### ISSUE TITLE
bug plz help me 

### ISSUE THREAD

**Issue by HashcatSec** [zile42O/panda-c2#1]
hey i have a probleme with the source idk where i can put my server

**Comment by zile42O** [comment]
Can you better describe the issue?

**Comment by HashcatSec** [comment]
when i enter go build -o c2
i throw me that 
-bash-5.1# go build -o c2
# golang.org/x/sys/unix
../go/src/golang.org/x/sys/unix/mremap.go:42:10: undefined: unsafe.Slice
../go/src/golang.org/x/sys/unix/syscall.go:83:16: undefined: unsafe.Slice
../go/src/golang.org/x/sys/unix/syscall_linux.go:1018:20: undefined: unsafe.Slice
../go/src/golang.org/x/sys/unix/syscall_linux.go:2300:9: undefined: unsafe.Slice
../go/src/golang.org/x/sys/unix/syscall_unix.go:118:7: undefined: unsafe.Slice
../go/src/golang.org/x/sys/unix/sysvshm_unix.go:33:7: undefined: unsafe.Slice
-bash-5.1#

**Comment by zile42O** [comment]
Did you setup a go .mod and go .sum files?

```
go mod init main
go mod tidy
```

**Comment by HashcatSec** [comment]
yeah of course you want my discord for help me or just here

**Comment by zile42O** [comment]
Provide me info about your golang version and OS

**Comment by HashcatSec** [comment]
Go 1.15 i think idk thé command for Know that

**Comment by zile42O** [comment]
Update your golang version
Do again 
```
go mod init main
go mod tidy
go build
```
Send me output

**Comment by HashcatSec** [comment]
go version go1.15.15 linux/amd64

**Comment by HashcatSec** [comment]
-bash-5.1# go mod init main
go mod tidy
go build
go mod init: go.mod already exists
go: downloading github.com/fatih/color v1.15.0
go: downloading github.com/go-sql-driver/mysql v1.7.1
go: downloading github.com/mackerelio/go-osstat v0.2.4
go: downloading github.com/mattn/go-colorable v0.1.13
go: downloading golang.org/x/sys v0.6.0
go: downloading github.com/mattn/go-isatty v0.0.17
# golang.org/x/sys/unix
../go/pkg/mod/golang.org/x/sys@v0.6.0/unix/syscall.go:83:16: undefined: unsafe.Slice
../go/pkg/mod/golang.org/x/sys@v0.6.0/unix/syscall_linux.go:1018:20: undefined: unsafe.Slice
../go/pkg/mod/golang.org/x/sys@v0.6.0/unix/syscall_linux.go:2289:9: undefined: unsafe.Slice
../go/pkg/mod/golang.org/x/sys@v0.6.0/unix/syscall_unix.go:118:7: undefined: unsafe.Slice
../go/pkg/mod/golang.org/x/sys@v0.6.0/unix/sysvshm_unix.go:33:7: undefined: unsafe.Slice
note: module requires Go 1.17

**Comment by zile42O** [comment]
You already have answer in output, update your golang version to minimal 1.17
